spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(k+YNQnfgXLUX1PDk9YMdGz7C9F3JjxpWffepOzubWOE5Su8V7NHJcB5/3KcAxcUOBkGFEQZ28NWO5NQGq8yMUVx+Pjq8WIJFU2YGDrkV028X4G7nOnAoi7nLzDyFE8ABwrD+ZJb0fTN/qNRJ25ZVsw==)
    username: ENC(8XqLpLAUgoDfIOwT1C83NA==)
    password: ENC(skmX3ubPYfiGoL9F+C9m+fdjDXcZ4rOt)
#    url: jdbc:mysql://localhost:3306/liargame
#    username: root
#    password: liargamedevelop
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
#logging:
#  level:
#    org:
#      springframework:
#        web: DEBUG

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

rabbitmq:
  username: ENC(PGk5csF3O3aPSZCkMVic5Q==)
  password: ENC(34qp2Zzfp7zTmZheMU+hoeAVdv+1pFmS)
  host: ENC(Ul814bw3RoDPTywtNJLpx3hm6EplmznQ)

category:
  keywords:
    음식:
      - "피자"
      - "떡볶이"
      - "비빔밥"
      - "치킨"
      - "족발"
      - "순대"
    스포츠:
      - "축구"
      - "농구"
      - "야구"
      - "발리볼"
      - "골프"
      - "컬링"
    동물:
      - "개"
      - "소"
      - "토끼"
      - "염소"
      - "표범"
      - "치타"
      - "재규어"
      - "돼지"
      - "고래"
    연예인:
      - "수지"
      - "아이유"
      - "제니"
      - "정국"
      - "RM"
      - "지수"
      - "지드래곤"
    장소:
      - "야구장"
      - "스키장"
      - "카페"
      - "초등학교"
      - "호텔"
      - "클럽"

jwt:
  secret: Mjg1MGNjZTAtOWFlMC00YTdkLThmYWYtMDE0NDlmNDk0ZGZidGhpcy1pcy1saWFyLWdhbWUtand0LXRva2VuLWtleTljODBmZTU5LTY2ZjgtNDYzNC1hMjZmLTJlYjNmMzkxY2Q0MmQ3MDYzOWUxLTMyMjQtNDYwMS1hYTQwLTk5OWJiOWUwODI4NA==